/*************************************************************************************************************
 The MIT License
 
 Copyright (c) 2014-2022 David Dubbeldam, Sofia Calero, Thijs J.H. Vlugt.
 
 D.Dubbeldam@uva.nl      http://www.uva.nl/profiel/d/u/d.dubbeldam/d.dubbeldam.html
 S.Calero@tue.nl         https://www.tue.nl/en/research/researchers/sofia-calero/
 t.j.h.vlugt@tudelft.nl  http://homepage.tudelft.nl/v9k6y
 
 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without
 restriction, including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following
 conditions:
 
 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 *************************************************************************************************************/


public struct SKResidueAtomDefinition
{
  public let element: String
  public let type: String
  public let bondedAtoms: [String]

  public init(element: String, type: String, bondedAtoms: [String])
  {
    self.element = element
    self.type = type
    self.bondedAtoms = bondedAtoms
  }
}

extension SKElement
{
  public static let residueDefinitions: [String: SKResidueAtomDefinition] = [
    "ALA+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "ALA+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB", "C"]),
    "ALA+CB": SKResidueAtomDefinition(element: "C", type: "CH3E", bondedAtoms: ["CA"]),
    "ALA+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "ALA+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "ALA+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "ALA+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ALA+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ALA+HB1": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ALA+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ALA+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "ARG+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N ", "CB ", "C"]),
    "ARG+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA", "CG"]),
    "ARG+CD": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CG", "NE"]),
    "ARG+CG": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CB", "CD"]),
    "ARG+CZ": SKResidueAtomDefinition(element: "C", type: "CH0", bondedAtoms: ["NE", " NH1", "NH2"]),
    "ARG+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "ARG+NE": SKResidueAtomDefinition(element: "N", type: "NH1S", bondedAtoms: ["CD", "CZ"]),
    "ARG+NH1": SKResidueAtomDefinition(element: "N", type: "NC2", bondedAtoms: ["CZ"]),
    "ARG+NH2": SKResidueAtomDefinition(element: "N", type: "NC2", bondedAtoms: ["CZ"]),
    "ARG+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "ARG+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "ARG+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+HD2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+HD3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+HE": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+HG2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+HG3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+HH11": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+HH12": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+HH21": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ARG+HH22": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ASN+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "ASN+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB", "C"]),
    "ASN+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA", "CG"]),
    "ASN+CG": SKResidueAtomDefinition(element: "C", type: "CH0", bondedAtoms: ["CB", "OD1", "ND2"]),
    "ASN+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "ASN+ND2": SKResidueAtomDefinition(element: "N", type: "NH2", bondedAtoms: ["CG"]),
    "ASN+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "ASN+OD1": SKResidueAtomDefinition(element: "O", type: "OS", bondedAtoms: ["CG"]),
    "ASN+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "ASN+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ASN+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ASN+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ASN+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ASN+HD21": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ASN+HD22": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ASP+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "ASP+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N ", "CB", "C"]),
    "ASP+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA ", "CG"]),
    "ASP+CG": SKResidueAtomDefinition(element: "C", type: "CH0", bondedAtoms: ["CB ", "OD1", "OD2"]),
    "ASP+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C ", "CA"]),
    "ASP+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "ASP+OD1": SKResidueAtomDefinition(element: "O", type: "OC", bondedAtoms: ["CG"]),
    "ASP+OD2": SKResidueAtomDefinition(element: "O", type: "OC", bondedAtoms: ["CG"]),
    "ASP+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "ASP+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ASP+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ASP+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ASP+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "CYS+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "CYS+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB ", "C"]),
    "CYS+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA", "SG"]),
    "CYS+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "CYS+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "CYS+SG": SKResidueAtomDefinition(element: "S", type: "SH1E", bondedAtoms: ["CB"]),
    "CYS+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "CYS+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "CYS+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "CYS+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "CYS+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLN+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "GLN+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB", "C"]),
    "GLN+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA ", "CG"]),
    "GLN+CD": SKResidueAtomDefinition(element: "C", type: "CH0", bondedAtoms: ["CG", "NE2", "OE1"]),
    "GLN+CG": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CB", "CD"]),
    "GLN+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C ", "CA"]),
    "GLN+NE2": SKResidueAtomDefinition(element: "N", type: "NH2", bondedAtoms: ["CD"]),
    "GLN+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "GLN+OE1": SKResidueAtomDefinition(element: "O", type: "OS", bondedAtoms: ["CD"]),
    "GLN+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "GLN+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLN+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLN+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLN+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLN+HG2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLN+HG3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLN+HE21": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLN+HE22": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLU+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "GLU+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB", "C"]),
    "GLU+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA", "CG"]),
    "GLU+CD": SKResidueAtomDefinition(element: "C", type: "CH0", bondedAtoms: ["CG", "OE1 ", "OE2"]),
    "GLU+CG": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CB ", "CD"]),
    "GLU+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "GLU+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "GLU+OE1": SKResidueAtomDefinition(element: "O", type: "OC", bondedAtoms: ["CD"]),
    "GLU+OE2": SKResidueAtomDefinition(element: "O", type: "OC", bondedAtoms: ["CD"]),
    "GLU+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "GLU+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLU+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLU+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLU+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLU+HG2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLU+HG3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLY+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "GLY+CA": SKResidueAtomDefinition(element: "C", type: "CH2G", bondedAtoms: ["N", "C"]),
    "GLY+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "GLY+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "GLY+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "GLY+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLY+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLY+HA2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLY+HA3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLY+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLY+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLY+HG2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "GLY+HG3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "HIS+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "HIS+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB", "C"]),
    "HIS+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA", "CG"]),
    "HIS+CD2": SKResidueAtomDefinition(element: "C", type: "CR1H", bondedAtoms: ["CG ", "NE2"]),
    "HIS+CE1": SKResidueAtomDefinition(element: "C", type: "CRHH", bondedAtoms: ["ND1", "NE2"]),
    "HIS+CG": SKResidueAtomDefinition(element: "C", type: "C5", bondedAtoms: ["CB", "CD2", "ND1"]),
    "HIS+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "HIS+ND1": SKResidueAtomDefinition(element: "N", type: "NH1S", bondedAtoms: ["CG ", "CE1"]),
    "HIS+NE2": SKResidueAtomDefinition(element: "N", type: "NH1S", bondedAtoms: ["CD2", "CE1"]),
    "HIS+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "HIS+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "HIS+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "HIS+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "HIS+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "HIS+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "HIS+HD1": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "HIS+HD2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "HIS+HE1": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "HOH+O": SKResidueAtomDefinition(element: "C", type: "HOH", bondedAtoms: []),
    "HOH+H": SKResidueAtomDefinition(element: "H", type: "HOH", bondedAtoms: []),
    "ILE+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "ILE+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N ", "CB ", "C"]),
    "ILE+CB": SKResidueAtomDefinition(element: "C", type: "CH1S", bondedAtoms: ["CA", "CG1", "CG2"]),
    "ILE+CD1": SKResidueAtomDefinition(element: "C", type: "CH3E", bondedAtoms: ["CG1"]),
    "ILE+CG1": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CB ", "CD1"]),
    "ILE+CG2": SKResidueAtomDefinition(element: "C", type: "CH3E", bondedAtoms: ["CB"]),
    "ILE+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "ILE+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "ILE+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "ILE+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ILE+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ILE+HB": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ILE+HG12": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ILE+HG13": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ILE+HG21": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ILE+HG22": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ILE+HG23": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ILE+HD11": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ILE+HD12": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "ILE+HD13": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LEU+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "LEU+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N ", "CB", "C"]),
    "LEU+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA ", "CG"]),
    "LEU+CD1": SKResidueAtomDefinition(element: "C", type: "CH3E", bondedAtoms: ["CG"]),
    "LEU+CD2": SKResidueAtomDefinition(element: "C", type: "CH3E", bondedAtoms: ["CG"]),
    "LEU+CG": SKResidueAtomDefinition(element: "C", type: "CH1S", bondedAtoms: ["CB ", "CD1", "CD2"]),
    "LEU+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C ", "CA"]),
    "LEU+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "LEU+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LEU+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LEU+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LEU+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LEU+HD11": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LEU+HD12": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LEU+HD13": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LEU+HD21": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LEU+HD22": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LEU+HD23": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LEU+HG": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LYS+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA ", "O"]),
    "LYS+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N ", "CB", "C"]),
    "LYS+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA ", "CG"]),
    "LYS+CD": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CG ", "CE"]),
    "LYS+CE": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CD ", "NZ"]),
    "LYS+CG": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CB ", "CD"]),
    "LYS+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C  ", "CA"]),
    "LYS+NZ": SKResidueAtomDefinition(element: "N", type: "NH3", bondedAtoms: ["CE"]),
    "LYS+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "LYS+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "LYS+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LYS+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LYS+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LYS+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LYS+HG2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LYS+HG3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LYS+HD2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LYS+HD3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LYS+HE2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "LYS+HE3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "MET+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA ", "O"]),
    "MET+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB", "C"]),
    "MET+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA ", "CG"]),
    "MET+CE": SKResidueAtomDefinition(element: "C", type: "CH3E", bondedAtoms: ["SD"]),
    "MET+CG": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CB ", "SD"]),
    "MET+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "MET+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "MET+SD": SKResidueAtomDefinition(element: "S", type: "SM", bondedAtoms: ["CG ", "CE"]),
    "MET+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "MET+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PHE+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "PHE+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB", "C"]),
    "PHE+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA", "CG"]),
    "PHE+CD1": SKResidueAtomDefinition(element: "C", type: "CR1E", bondedAtoms: ["CG ", "CE1"]),
    "PHE+CD2": SKResidueAtomDefinition(element: "C", type: "CR1E", bondedAtoms: ["CG ", "CE2"]),
    "PHE+CE1": SKResidueAtomDefinition(element: "C", type: "CR1E", bondedAtoms: ["CD1", "CZ"]),
    "PHE+CE2": SKResidueAtomDefinition(element: "C", type: "CR1E", bondedAtoms: ["CD2 ", "CZ"]),
    "PHE+CG": SKResidueAtomDefinition(element: "C", type: "CF", bondedAtoms: ["CB ", "CD1", "CD2"]),
    "PHE+CZ": SKResidueAtomDefinition(element: "C", type: "CR1E", bondedAtoms: ["CE1", "CE2"]),
    "PHE+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C ", "CA"]),
    "PHE+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "PHE+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "PHE+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PHE+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PHE+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PHE+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PHE+HD1": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PHE+HD2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PHE+HE1": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PHE+HE2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PHE+HZ": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PRO+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "PRO+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB", "C"]),
    "PRO+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA", "CG"]),
    "PRO+CD": SKResidueAtomDefinition(element: "C", type: "CH2P", bondedAtoms: ["N", "CG"]),
    "PRO+CG": SKResidueAtomDefinition(element: "C", type: "CH2P", bondedAtoms: ["CB", "CD"]),
    "PRO+N": SKResidueAtomDefinition(element: "N", type: "N", bondedAtoms: ["-C", "CA", "CD"]),
    "PRO+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "PRO+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "PRO+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PRO+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PRO+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PRO+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PRO+HD2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PRO+HD3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PRO+HG2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "PRO+HG3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "SER+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "SER+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB", "C"]),
    "SER+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA", "OG"]),
    "SER+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "SER+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "SER+OG": SKResidueAtomDefinition(element: "O", type: "OH1", bondedAtoms: ["CB"]),
    "SER+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "SER+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "SER+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "SER+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "SER+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "THR+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "THR+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB", "C"]),
    "THR+CB": SKResidueAtomDefinition(element: "C", type: "CH1S", bondedAtoms: ["CA", "CG2", "OG1"]),
    "THR+CG2": SKResidueAtomDefinition(element: "C", type: "CH3E", bondedAtoms: ["CB"]),
    "THR+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "THR+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "THR+OG1": SKResidueAtomDefinition(element: "O", type: "OH1", bondedAtoms: ["CB"]),
    "THR+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "THR+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "THR+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "THR+HB": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "THR+HG1": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "THR+HG21": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "THR+HG22": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "THR+HG23": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "THR+HH2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TRP+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "TRP+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N ", "CB", "C"]),
    "TRP+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA", "CG"]),
    "TRP+CD1": SKResidueAtomDefinition(element: "C", type: "CR1E", bondedAtoms: ["CG ", "NE1"]),
    "TRP+CD2": SKResidueAtomDefinition(element: "C", type: "CW", bondedAtoms: ["CG ", " CE2", "CE3"]),
    "TRP+CE2": SKResidueAtomDefinition(element: "C", type: "CW", bondedAtoms: ["CD2 ", "CZ2", "NE1"]),
    "TRP+CE3": SKResidueAtomDefinition(element: "C", type: "CR1E", bondedAtoms: ["CD2", "CZ3"]),
    "TRP+CG": SKResidueAtomDefinition(element: "C", type: "C5W", bondedAtoms: ["CB ", "CD1", "CD2"]),
    "TRP+CH2": SKResidueAtomDefinition(element: "C", type: "CR1W", bondedAtoms: ["CZ2", "CZ3"]),
    "TRP+CZ2": SKResidueAtomDefinition(element: "C", type: "CR1W", bondedAtoms: ["CE2", "CH2"]),
    "TRP+CZ3": SKResidueAtomDefinition(element: "C", type: "CR1E", bondedAtoms: ["CE3", "CH2"]),
    "TRP+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "TRP+NE1": SKResidueAtomDefinition(element: "N", type: "NH1S", bondedAtoms: ["CD1 ", "CE2"]),
    "TRP+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "TRP+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "TRP+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TRP+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TRP+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TRP+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TRP+HD1": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TRP+HE1": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TRP+HE3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TRP+HZ2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TRP+HZ3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TRP+HH2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TYR+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "TYR+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB", "C"]),
    "TYR+CB": SKResidueAtomDefinition(element: "C", type: "CH2E", bondedAtoms: ["CA", "CG"]),
    "TYR+CD1": SKResidueAtomDefinition(element: "C", type: "CR1E", bondedAtoms: ["CG", "CE1"]),
    "TYR+CD2": SKResidueAtomDefinition(element: "C", type: "CR1E", bondedAtoms: ["CG", "CE2"]),
    "TYR+CE1": SKResidueAtomDefinition(element: "C", type: "CR1E", bondedAtoms: ["CD1", "CZ"]),
    "TYR+CE2": SKResidueAtomDefinition(element: "C", type: "CR1E", bondedAtoms: ["CD2", "CZ"]),
    "TYR+CG": SKResidueAtomDefinition(element: "C", type: "CY", bondedAtoms: ["CB", "CD1", "CD2"]),
    "TYR+CZ": SKResidueAtomDefinition(element: "C", type: "CY2", bondedAtoms: ["CE1", "CE2", "OH"]),
    "TYR+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "TYR+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "TYR+OH": SKResidueAtomDefinition(element: "O", type: "OH1", bondedAtoms: ["CZ"]),
    "TYR+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "TYR+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TYR+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TYR+HB2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TYR+HB3": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TYR+HD1": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TYR+HD2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TYR+HE1": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "TYR+HE2": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "VAL+C": SKResidueAtomDefinition(element: "C", type: "C", bondedAtoms: ["CA", "O"]),
    "VAL+CA": SKResidueAtomDefinition(element: "C", type: "CH1E", bondedAtoms: ["N", "CB", "C"]),
    "VAL+CB": SKResidueAtomDefinition(element: "C", type: "CH1S", bondedAtoms: ["CA", "CG1", "CG2"]),
    "VAL+CG1": SKResidueAtomDefinition(element: "C", type: "CH3E", bondedAtoms: ["CB"]),
    "VAL+CG2": SKResidueAtomDefinition(element: "C", type: "CH3E", bondedAtoms: ["CB"]),
    "VAL+N": SKResidueAtomDefinition(element: "N", type: "NH1", bondedAtoms: ["-C", "CA"]),
    "VAL+O": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "VAL+OXT": SKResidueAtomDefinition(element: "O", type: "O", bondedAtoms: ["C"]),
    "VAL+H": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "VAL+HA": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "VAL+HB": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "VAL+HG11": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "VAL+HG12": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "VAL+HG13": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "VAL+HG21": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "VAL+HG22": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
    "VAL+HG23": SKResidueAtomDefinition(element: "H", type: "H", bondedAtoms: []),
  ]
}
